# -*- coding: utf-8 -*-
"""Brain_Tumor_Detection_Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/184BE5k3fF8S60C1luuSFyDAvEqzluzjv
"""

# 1. Install required packages
!pip install google-genai gradio opencv-python-headless numpy pandas scikit-learn

import os
import cv2
import numpy as np
import pandas as pd
import datetime
import random
import time
import joblib
from sklearn.ensemble import RandomForestClassifier

# 2. IMAGE PROCESSING LAYER (Reading both 'yes' and 'no' folders)
X_images = []
y_labels = []

# Paths to your local folders in Colab
no_folder = '/content/no'
yes_folder = '/content/yes'

# Process Normal Scans (Label = 0)
if os.path.exists(no_folder):
    print(f"📁 Processing normal images from '{no_folder}'...")
    for file_name in os.listdir(no_folder):
        img = cv2.imread(os.path.join(no_folder, file_name), cv2.IMREAD_GRAYSCALE)
        if img is None: continue
        img_resized = cv2.resize(img, (64, 64))
        X_images.append(img_resized.flatten())
        y_labels.append(0)

# Process Tumor Scans (Label = 1)
if os.path.exists(yes_folder):
    print(f"📁 Processing tumor images from '{yes_folder}'...")
    for file_name in os.listdir(yes_folder):
        img = cv2.imread(os.path.join(yes_folder, file_name), cv2.IMREAD_GRAYSCALE)
        if img is None: continue
        img_resized = cv2.resize(img, (64, 64))
        X_images.append(img_resized.flatten())
        y_labels.append(1) # Label 1 = Tumor Detected

X = np.array(X_images)
y = np.array(y_labels)

# 3. Train the ML Brain on both classes
if len(X) > 0:
    brain_model = RandomForestClassifier(random_state=42)
    brain_model.fit(X, y)
    joblib.dump(brain_model, 'brain_tumor_model.pkl')
    print(f"🧠 System Message: Machine Learning Brain trained successfully on {len(X)} total images (Tumor & Normal)!")
else:
    print("⚠️ Error: No images were found in /content/no or /content/yes. Check your folder sidebar!")

import os
import cv2
import numpy as np
from google import genai
from google.genai import types

# 1. INITIALIZE AGENT BRAIN
# Best Practice: Store your API key in an environment variable named GEMINI_API_KEY.
# genai.Client() automatically detects GEMINI_API_KEY if api_key is not passed.
# FIX: Assign the API key directly. For better security, consider setting it as an environment variable named 'GEMINI_API_KEY' first.
api_key = "enter_api_kry"
client = genai.Client(api_key=api_key)

# 2. DEFINING THE MACHINE LEARNING TOOL FOR THE AGENT
def classify_mri_scan(image_path: str) -> str:
    """Analyzes a raw brain MRI scan image file and returns a machine learning
    prediction indicating if a tumor is detected or if the scan is normal.

    Args:
        image_path (str): The local file path to the brain MRI scan image.

    Returns:
        str: Diagnostic result string from the machine learning model.
    """
    if not image_path:
        return "Error: No image file path provided."

    # Read image in grayscale using OpenCV
    img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        return f"Error: Unable to load or read image file at '{image_path}'."

    # Preprocess: resize to (64x64) and reshape to a standard 2D sample array (1, 4096)
    img_resized = cv2.resize(img, (64, 64))
    flattened_img = img_resized.flatten().reshape(1, -1)

    # Execute prediction with error checks
    try:
        if 'brain_model' not in globals():
            return "Error: 'brain_model' is not loaded in current runtime environment."

        prediction = brain_model.predict(flattened_img)[0]

        if prediction == 1:
            return "ML Model Result: ⚠️ TUMOR DETECTED"
        else:
            return "ML Model Result: ✅ NORMAL (No tumor patterns detected)"

    except Exception as e:
        return f"Error during model prediction: {str(e)}"

print("🤖 System Message: Agent Tools and Reasoning Brain initialized.")

import datetime
import os
import gradio as gr
import pandas as pd
from PIL import Image
from google import genai
from google.genai import types

# ---------------------------------------------------------------------------
# 0. INITIALIZATION & MOCK TOOL SETUP
# ---------------------------------------------------------------------------
# Initialize Gemini Client (Ensure GEMINI_API_KEY environment variable is set)
# FIX: Pass the 'api_key' variable directly to the client constructor.
client = genai.Client(api_key=api_key)

# Ledger state history
tumor_agent_history = []


def classify_mri_scan(image_path: str) -> str:
    """
    Tool function to run an automated diagnostic classifier on a brain MRI scan.

    Args:
        image_path (str): Filepath to the patient's MRI image.
    """
    # NOTE: Replace this mock response with your actual ML model inference logic
    return (
        "Classification Model Output: High probability of abnormal mass / tumor "
        "(Glioma pattern detected, confidence: 93.8%)."
    )


# ---------------------------------------------------------------------------
# 1. CORE AGENT LOGIC FUNCTION
# ---------------------------------------------------------------------------
def ai_agent_clinic_handler(patient_id, scan_type, mri_image_path):
    global tumor_agent_history

    if not mri_image_path:
        return (
            "⚠️ **Error:** Please upload a valid brain MRI scan image to proceed with the diagnostic sequence.",
            pd.DataFrame(tumor_agent_history)
        )

    try:
        # 1. Load image using PIL so Gemini can process the vision payload
        img = Image.open(mri_image_path)

        system_instruction = (
            "You are an autonomous Lead AI Radiologist Assistant. "
            "You have access to a tool named `classify_mri_scan`. When given a patient case, "
            "you MUST invoke this tool to evaluate the scan, then synthesize a professional, "
            "structured medical report containing: Clinical Findings, Diagnostic Impression, "
            "and Recommended Action Plan/Protocols."
        )

        doctor_prompt = (
            f"Please conduct a diagnostic analysis on the following patient case:\n"
            f"• Patient ID: {patient_id}\n"
            f"• Scan Modality: {scan_type}\n"
            f"• File Location: {mri_image_path}"
        )

        # 2. Call Gemini API with Tooling + Image Multimodal Input
        response = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=[doctor_prompt, img],
            config=types.GenerateContentConfig(
                system_instruction=system_instruction,
                tools=[classify_mri_scan],
                temperature=0.2
            )
        )

        report_text = response.text if response.text else "No report generated."

    except Exception as e:
        report_text = f"❌ **System Execution Error:** {str(e)}"

    # 3. Evaluate decision status for database logging
    if "NORMAL" in report_text.upper() and "TUMOR" not in report_text.upper():
        agent_decision = "🟢 Normal / Clear"
    else:
        agent_decision = "🔴 Tumor Flagged"

    # 4. Append entry to clinical history ledger
    timestamp_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    tumor_agent_history.append({
        "Timestamp": timestamp_str,
        "Patient ID": patient_id,
        "Scan Modality": scan_type,
        "Agent Decision": agent_decision,
        "Report Excerpt": report_text[:120].replace("\n", " ") + "..."
    })

    return report_text, pd.DataFrame(tumor_agent_history)


# ---------------------------------------------------------------------------
# 2. GRADIO INTERFACE DESIGN (CUSTOM THEME & LAYOUT)
# ---------------------------------------------------------------------------
custom_theme = gr.themes.Soft(
    primary_hue="teal",
    secondary_hue="slate",
    neutral_hue="slate",
    font=[gr.themes.GoogleFont("Inter"), "ui-sans-serif", "system-ui"]
)

with gr.Blocks(theme=custom_theme, title="Brain Tumor AI Agent Workspace") as demo:

    # Custom Header Banner
    gr.HTML("""
        <div style="background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%); padding: 24px; border-radius: 12px; margin-bottom: 20px; color: white;">
            <h1 style="margin: 0; font-size: 28px; display: flex; align-items: center; gap: 10px;">
                🧠 Autonomous Brain Tumor AI Radiologist
            </h1>
            <p style="margin: 8px 0 0 0; color: #94a3b8; font-size: 14px;">
                Computer Engineering Portfolio Workspace • Autonomous Diagnostic Synthesis & Ledger System
            </p>
        </div>
    """)

    with gr.Row(equal_height=False):

        # Left Column: Inputs
        with gr.Column(scale=1):
            with gr.Group():
                gr.Markdown("#### 📥 Patient & Diagnostic Inputs")
                p_id = gr.Textbox(
                    label="Patient Identifier",
                    value="CASE-9842",
                    placeholder="e.g. PATIENT-102"
                )
                s_type = gr.Dropdown(
                    choices=["MRI T1-Weighted", "MRI T2-Weighted", "MRI T2-FLAIR"],
                    label="Scan Modality Sequence",
                    value="MRI T2-FLAIR"
                )
                input_img = gr.Image(
                    label="Upload Brain MRI Scan",
                    type="filepath",
                    height=280
                )

                btn_analyze = gr.Button(
                    "⚡ Execute Agent Diagnostics",
                    variant="primary",
                    size="lg"
                )

        # Right Column: System Output Terminal
        with gr.Column(scale=1.5):
            with gr.Group():
                gr.Markdown("#### 📝 Autonomous Medical Report Output")
                agent_report = gr.Markdown(
                    value="*Awaiting MRI scan input and execution trigger...*",
                    container=True
                )

    gr.Markdown("---")

    # Bottom Ledger Database View
    with gr.Group():
        gr.Markdown("### 🗄️ Clinical Transaction History Ledger")
        ledger_table = gr.DataFrame(
            label="System State Log",
            value=pd.DataFrame(tumor_agent_history),
            interactive=False,
            wrap=True
        )

    # Event Binding
    btn_analyze.click(
        fn=ai_agent_clinic_handler,
        inputs=[p_id, s_type, input_img],
        outputs=[agent_report, ledger_table],
        api_name="analyze_scan"
    )

# Launch app
if __name__ == "__main__":
    demo.launch(share=True, debug=True)